SET SERVEROUTPUT ON;

DECLARE

ctx DBMS_XMLGEN.CTXHANDLE;
XMLOUT CLOB;

BEGIN
      ctx := DBMS_XMLGEN.newContext('SELECT F.NOME AS FUNCIONARIO_NOME, F.CARGO.NOME_CARGO AS CARGO, F.SEXO AS SEXO FROM TB_FUNCIONARIO F');
      DBMS_XMLGEN.setRowsetTag(ctx, 'FUNCIONARIOS');
      DBMS_XMLGEN.setRowTag(ctx, 'FUNCIONARIO');
      XMLOUT := DBMS_XMLGEN.getXML(ctx);
      DBMS_OUTPUT.PUT_LINE(XMLOUT);
      DBMS_XMLGEN.closeContext(ctx);
END;
/